### PR TITLE
Fixed tapAsync of undefined bug

### LINKED ISSUE #44: Cannot read property 'tapAsync' of undefined
Plugin doesn't work with ejected create-react-app, webpack version is  4.29.6

### PR DESCRIPTION
**Pull request by SpyTec**
Fixes #44 

This maps current events to newer ones though a mapping object

### CODE REVIEW

**Comment by numical** [comment]
Hi @SpyTec,
Thanks for the PR.
Can I check whether the TypeError messages you make in [issue 44](https://github.com/numical/style-ext-html-webpack-plugin/issues/44) relate to this change?
Or is this a fix to those?
If so I'm minded to accept this PR even though we have not yet extended the testing to HtmlWebpack 4 as it fixes an immediate need. 
Then look to extend testing...

**Comment by SpyTec** [comment]
Hey @numical,

I didn't change anything, but the error I encountered no longer occurs. I've only tested it on my own project and I do not know whether this change will break something else

**Comment by numical** [comment]
Okey dokey.  Then I will extend testing before putting it in.
FYI - working on branch [feature/html-webpack-plugin-4-support](https://github.com/numical/style-ext-html-webpack-plugin/tree/feature/html-webpack-plugin-4-support)

**Comment by numical** [comment]
There was a little more to do to support HtmlWebpack v4.x.
This is now under test on branch  [feature/html-webpack-plugin-4-support](https://github.com/numical/style-ext-html-webpack-plugin/tree/feature/html-webpack-plugin-4-support) and I will alert you as soon as it is ready.
Thanks for the suggestion.

**Pull request closed without merging**
