### PR TITLE
now supports multiple input/output and sass compilation

### PR DESCRIPTION
**Pull request by hagmandan**
same folder structure as before, except now with `.scss` files instead of `.css` files.

Here's my webpack.config.js for comparison:

```
var webpack = require('webpack');
var UglifyJsPlugin = webpack.optimize.UglifyJsPlugin;
var path = require('path');
var env = require('yargs').argv.mode; /* TODO: consider breaking this out into a build.js file */
var pkg = require('./package.json');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var StyleExtHtmlWebpackPlugin = require('style-ext-html-webpack-plugin');
var ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin');

// TODO: instead of manually adding each page name here,
//       we should crawl the folders under /pages/* and get those names
var pageNames = ['page1','page2-demo','example-page-3'];
var entry = {};
var plugins = [
  new webpack.ProvidePlugin({
    'Map': 'core-js/es6/map'
  })
];
var extractTexts = {};

// if we're building it, minify it
if (env === 'build') {
  plugins.push(new UglifyJsPlugin({ minimize: true }));
}

//////////////////////////////////////////////////////
// setup output config here
var output = {
  path: __dirname + '/dist',
  filename: '[name]-scripts.js',
  chunkFilename: '[id].bundle.js'
};

//////////////////////////////////////////////////////
// setup loaders config here
var loaders = [
  {
    test: /\.js$/,
    loader: 'babel',
    include: [
      path.resolve(__dirname, 'src', 'pages'),
      path.resolve(__dirname, 'src', 'shared', 'scripts')
    ],
    query: {
      presets: ['es2015'],
      plugins: [
        'babel-plugin-add-module-exports',
        'transform-class-properties',
        'transform-es2015-classes',
        'transform-es2015-destructuring',
        'transform-object-rest-spread'
      ]
    }
  },
  {
    test: /\.js$/,
    loader: 'eslint-loader',
    exclude: /node_modules/,
    include: [
      path.resolve(__dirname, 'src', 'pages'),
      path.resolve(__dirname, 'src', 'shared')
    ]
  },
  {
    test: /\.hbs/,
    loader: 'handlebars',
    query: {
      partialDirs: [
        path.resolve(__dirname, 'src', 'shared', 'templates')
      ],
      helperDirs: [
        path.resolve(__dirname, 'src', 'shared', 'scripts')
      ]
    }
  }/*,
  {
    test: /\.scss$/i,
    loaders: ['css-loader', 'sass-loader']
  }*/
];

// page construction happens here: we iterate through all page names we want to create,
// and extract all necessary css/js after compiling down our handlebars templates
pageNames.forEach((pageName) => {
  // setup entry object
  // TODO: see top of page; goal = crawl directory structure
  entry[pageName] = `./src/pages/${pageName}`;
  extractTexts[pageName] = new ExtractTextPlugin('[name]-styles.css');

  loaders.push({
    test: /\.scss$/i,
    loader: extractTexts[pageName].extract('style','css!sass'),
    // test: /\.scss$/,
    // loader: extractTexts[pageName].extract('style', 'css?sourceMap', 'sass?sourceMap'),
    include: [
      path.resolve(__dirname, 'src', 'pages', pageName)
    ]
  });

  plugins.push(new HtmlWebpackPlugin({
    chunks: [pageName],
    filename: `${pageName}.html`,
    template: `src/pages/${pageName}/template.hbs`
  }));

  plugins.push(extractTexts[pageName]);
});
plugins.push(new StyleExtHtmlWebpackPlugin());

plugins.push(new ScriptExtHtmlWebpackPlugin({
  inline: pageNames.map((pageName) => {
    return `${pageName}-scripts`;
  })
}));


//////////////////////////////////////////////////////
// setup webpack config
var config = {
  entry: entry,
  output: output,
  module: {
    loaders: loaders
  },
  node: {
    fs: 'empty' // necessary to avoids error messages
  },
  resolve: {
    root: path.resolve('./src'),
    extensions: ['', '.js']
  },
  plugins: plugins
};

module.exports = config;

```

### CODE REVIEW

**Comment by hagmandan** [comment]
### folder structure example

.
+-- node_modules
+-- build
+-- dist // this is what the pages build into
| +-- page1.html
| +-- page2.html
| +-- page3.html
+-- src
| +-- pages
| | +-- page1
| | | +-- template.hbs
| | | +-- index.js
| | | +-- styles.scss
| | +-- page2
| | | +-- template.hbs
| | | +-- index.js
| | | +-- styles.scss
| | +-- page3
+-- package.json
+-- webpack.config.js
+-- //etc...

**Comment by numical** [comment]
Hi,
Had a chance to take a look.
We might be able to do this without any change - basically use a repeated version of the following [use case](https://github.com/numical/style-ext-html-webpack-plugin#use-case-internalize-critical-css-with-all-other-css-in-an-external-file).
In other words, just as your webpack config loops to configure an ExtractTextPugin instance for each page, push the StyleExtHtmlWebpackPlugin instantiation into that loop, giving each instance an explicit .css file to target. 
If you have already tried this, do let me know the gotcha I have missed!

**Comment by hagmandan** [comment]
Hey,
Thanks for taking a look at this! So here's what I tried:
```
pluginsConfig.push(extractPlugin[pageName]);
+
+    pluginsConfig.push(new StyleExtHtmlWebpackPlugin(`${pageName}-styles.css`));
   });
 
   // now we extract all <link> to inline <style>
-  pluginsConfig.push(new StyleExtHtmlWebpackPlugin());
+  // pluginsConfig.push(new StyleExtHtmlWebpackPlugin());
 
```

and I error out when I build with:
```
ERROR in   StyleExtHtmlWebpackPluginError: S{PLUGIN} could not find <link> element to replace; available head elements: [{"tagName":"style","closeTag":true,"innerHTML":"html {\n  font-size: 111%;\n  /* for testing only */\n  color: r  gba(0, 0, 0, 0.99);\n  /* for testing only */\n  background: #ff2c33; }\n  html body {\n    padding: 111px;\n    background: rgba(255, 255, 255, 0.5); }\n"}]
  
  - plugin.js:10 error
    [static-page-generator_trunk]/[style-ext-html-webpack-plugin]/lib/plugin.js:10:15
  
  - plugin.js:62 replaceLinkTag
    [static-page-generator_trunk]/[style-ext-html-webpack-plugin]/lib/plugin.js:62:3
...
ERROR in   StyleExtHtmlWebpackPluginError: StyleExtHtmlWebpackPlugin could not find ExtractTextWebpackPlugin's generated .css file; available files: 'page2-demo-scripts.js,page1-scripts.js,example-page-3-scripts.js,page2-demo-styles.  css,example-page-3-styles.css,page1.html'
  
  - plugin.js:10 error
    [static-page-generator_trunk]/[style-ext-html-webpack-plugin]/lib/plugin.js:10:15
  
  - plugin.js:23 findGeneratedCssFile
    [static-page-generator_trunk]/[style-ext-html-webpack-plugin]/lib/plugin.js:23:3
...
ERROR in   StyleExtHtmlWebpackPluginError: StyleExtHtmlWebpackPlugin could not find ExtractTextWebpackPlugin's generated .css file; available files: 'page2-demo-scripts.js,page1-scripts.js,example-page-3-scripts.js,example-page-3-sty  les.css,page1.html,page2-demo.html'
  
  - plugin.js:10 error
    [static-page-generator_trunk]/[style-ext-html-webpack-plugin]/lib/plugin.js:10:15
  
  - plugin.js:23 findGeneratedCssFile
    [static-page-generator_trunk]/[style-ext-html-webpack-plugin]/lib/plugin.js:23:3
```

The bit of investigating I did looks like every attempt to extract the css after the first try fires `validatePassedCssFilename` and `cssFilename` is now equal to "the previously parsed file"; it attempts to replace a `<style>` tag now, and returns the same parsed css file each time (since the `matchFn` returns true for `filename === cssFilename`) and doesn't move onto another css to process (unless I'm misunderstanding that bit...).

Thoughts on alternatives to getting this to work?

**Comment by numical** [comment]
Oh dear - time to write a failing test (that should be easy!) and then check out your suggested fix.
This is taking more time than usual - sorry - a little busy.

**Comment by hagmandan** [comment]
No worries! I'm trying to see if there's a way to fix this combining what you suggested as a work around and debugging the plugin differently.

Basically right now, after the first iteration through, the next css file attempts to get processed, but the `pluginArgs` is actually set to the recently swapped `style` tag; I think if we can do a check to see if `pluginArgs` is set to a style, we skip over it (without reassigning `cssFilename`) and continue onwards...

Still playing with this, will try to submit a new PR soon

**Comment by hagmandan** [comment]
Hey there,

SO i feel like i was able to update the plugin with less crazy checks all over the place; when you get a chance (the weekend is fine) can you take a look and let me know your thoughts? With the latest update, the method you suggested for getting my plugin to work (eg, throwing new instances of style-ext into my loop) now works beautifully.

Thanks again!

Dan

**Comment by numical** [comment]
Cool.  Thanks for continuing with this.
For my part, I have been working on the failing test - a bit of a rewrite of the test helpers was required.
You can now see it at [this branch](https://github.com/numical/style-ext-html-webpack-plugin/blob/support-multiple-entry-points/spec/core-spec.js#L384).  
My next steps are to merge in your stuff (which looks perfectly decent) and see if it all works.
However that's for tomorrow... my New Year's resolution to cycle to work every day is knackering me.
Thanks again for your perseverance :-)

**Comment by hagmandan** [comment]
My pleasure! i actually saw your last comment after i attempted to update some dependencies, so not sure if my latest update to my branch is worthwhile or not...

I'll take a look at your spec update tonight as well (and i have a similar resolution, so i totally understand! thanks again for the quick replies all around :) )

**Comment by numical** [comment]
Warning!  The test I created yesterday was incorrect.
A small matter of `chunks: 'page1'` instead of `chunks: ['page1']` for the `html-webpack-plugin` config.
Fixed and uploaded if you want to pull.
There's the best part of the evening wasted.

**Comment by numical** [comment]
Ok - finally got around to looking at your suggested implementation.
A couple of issues:
- `PROCESSED_FILES` : essentially global, well, module state that hangs around after the processing - not so good when webpack is in 'watch' mode and processing re-runs; we could probably clear it up in the 'emit' event but then the next issue comes up - do you want css files per page to be mutually exclusive - I would like a solution which leaves open the option of more flexibility;
- `pluginArgs.head[0].tagName === 'link'`: rather brittle as we have no control of the pluginArgs - this is more minor as we could be disciplined about ordering and, moreover, the whole `if` statement can probably be done without.

Ok - having poked holes, do I have an alternative solution yet ... nope.  But I am thinking about it...

**Comment by numical** [comment]
So the way we're going to go is to mirror html-webpack-plugin's [chunks](https://github.com/ampedandwired/html-webpack-plugin#configuration) config option.  Then instead of specifying a specifc .css file we specify all .css files related to a specific chunk.  This should make an obvious, if clunky, api where we map an html-web-pack instance to a style-ext-html-webpack-instance by defining both to use the same chunks:
```javascript
...
new HtmlWebPackPlugin({ chunks: ['xxx']}),
new HtmlWebPackPlugin({ chunks: ['yyy']}),
...
new StyleExtWebpackPlugin({ chunks: ['xxx']}),
new StyleExtWebpackPlugin({ chunks: ['yyy']}),
...
```
To do this, first I must extend the config options - this is now committed on this feature [branch](https://github.com/numical/style-ext-html-webpack-plugin/tree/support-multiple-entry-points).
Next - the actual functionality...

**Comment by numical** [comment]
Just pushed a working implementation on feature [branch](https://github.com/numical/style-ext-html-webpack-plugin/tree/support-multiple-entry-points)
This is currently working only in node v6+ (?)
If that fits, could you give it a try?

**Comment by numical** [comment]
Implementation working on node v4+.
Pushed to master branch and published as version 3.1.0.
Hopefully this solves your problems.
Let me know otherwise.

**Comment by hagmandan** [comment]
Just following up! No issues and this works great :) thanks again for all your help!

**Comment by numical** [comment]
Brilliant. Thanks for letting me know.

---- On Tue, 31 Jan 2017 00:14:31 +0000 notifications@github.com wrote ----

Just following up! No issues and this works great :) thanks again for all your help!

**Pull request closed without merging**
