### PR TITLE
Fix case where publicPath is a URL

### LINKED ISSUE #33: Inlined styles link element is not removed from the HTML template
I'm using a very basic config copied from the readme and everything works fine, but the link tag for my CSS file is still present in the HTML template causing a 404 error in the browser.

### PR DESCRIPTION
**Pull request by jlowgren**
Fixes #33 

Not sure if others have experienced the exact same issue as me, but this "works on my machine".

To clarify; this part in `replaceTag.js`

```js
if (prefix) {
  cssFilename = path.join(prefix, cssFilename);
}
```

Would change a `publicPath` containing a URL from this:

```
https://www.example.com/somepath/critical.css
```

To this (note the missing slash following the protocol):

```
https:/www.example.com/somepath/critical.css
```

### CODE REVIEW

**Comment by gvitelli** [comment]
Hello.
Yes, the same happens in my project and came up with the same fix too. I almost made a new PR, but luckily I found this one to bump instead.
I've tried this and it fixes the problem. I'm glad to help if there is anything else needed to have this PR merged in master.
Cheers

**Comment by numical** [comment]
Thanks!
I'll need to add tests for different types of public path before I can commit.
Will get onto this as soon as I can.
Or if you have time to add to the PR: example test is [here](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/spec/helpers/main-tests.js#L294).

**Comment by jlowgren** [comment]
@numical Tests added, courtesy of @gvitelli. 🙇

**Comment by numical** [comment]
Thanks all!  Version 3.4.6 released with this PR.

**Pull request merged**
