### PR TITLE
Added webpack 4 support

### PR DESCRIPTION
**Pull request by SamDuvall**
https://github.com/numical/style-ext-html-webpack-plugin/issues/39

### CODE REVIEW

**Comment by CurtisHumphrey** [comment]
I just tested his PR and it works. Thanks @SamDuvall!

**Comment by kroko** [comment]
FYI.

* using [mini-css-extract-plugin](https://webpack.js.org/plugins/mini-css-extract-plugin/) which is kind of _webpack 4 way_
* considering _html-webpack-plugin_ with inject set to true and not specifying any template - vanilla settings
* two entries
* 7 JS chunks from which 1 is lazy loaded
* 2 CSS chunks from which 1 is lazy loaded

only one chunk gets inlined. and it is the lazy loaded chunk o_O

I know, this is bad report withot me giving code example and a bit offtopic, but IMHO label _adding webpack 4 support_ is misguiding as it should also include support for _mini-css-extract-plugin_ and [depreciate](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/782) _extract-text-webpack-plugin_

Pardon @CurtisHumphrey for giving you thumbs down at first 😄 , I ignored fact that it might work if you still somehow use `extract-text-webpack-plugin` in webpack 4

**Comment by kroko** [comment]
Solved by switching to [html-webpack-inline-source-plugin](https://github.com/DustinJackson/html-webpack-inline-source-plugin) 😄 

**Works**

* when *HtmlWebpackPlugin* uses `inject: true` on no template (thus under to hood default is called)
* when *HtmlWebpackPlugin* uses `inject: true` on custom template

**Does not work** 

* when *HtmlWebpackPlugin* uses `inject: false` on custom template based on [html-webpack-template](https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs), known issue https://github.com/DustinJackson/html-webpack-inline-source-plugin/issues/30

Example

```javascript
// ..

// ----------------
// HtmlWebpackPlugin
config.plugins.push(new HtmlWebpackPlugin({
  // ..
  filename: path.join(__dirname, 'public/index.html'),
  template: path.join(__dirname, 'src/html/index.template.ejs'),
  inject: false,
  inlineSource: '.css$',
  // ..
}));

// ----------------
// HtmlWebpackInlineSourcePlugin
config.plugins.push(new HtmlWebpackInlineSourcePlugin());

// ----------------
// MiniCssExtractPlugin
config.plugins.push(new MiniCssExtractPlugin({
  // ..
}));

// ..
```

```ejs
<!DOCTYPE html>
<html lang="en" class="noscript incapable">
<head>
  <meta charset="utf-8">
  <title><%= htmlWebpackPlugin.options.title || 'Webpack Test'%></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">

  <% for (var css in htmlWebpackPlugin.files.css) { %>
    <link href="<%= htmlWebpackPlugin.files.css[css] %>" rel="stylesheet" type="text/css">
  <% } %>
</head>
<body>
  <div class="app"></div>
  <script>
    window.__TEMPLATE_DATA__ = {};
  </script>

  <% for (var item in htmlWebpackPlugin.options.scripts) { %><%
      if (typeof item === 'string' || item instanceof String) { item = { src: item, type: 'text/javascript' } } %>
    <script<% for (var key in item) { %> <%= key %>="<%= item[key] %>"<% } %>></script>
  <% } %>

  <% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
    <script async src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
  <% } %>

</body>
</html>
```

So it covers "fast cases", but when custom template is needed, the solution is just to roll your own.

---

Add some key to *HtmlWebpackPlugin* config. In my case array holding regex expressions for stuff that should be inlined.

```javascript
// ..

// ----------------
// HtmlWebpackPlugin
config.plugins.push(new HtmlWebpackPlugin({
  // ..
  filename: path.join(__dirname, 'public/index.html'),
  template: path.join(__dirname, 'src/html/index.template.ejs'),
  inject: false,
  inlineCSSRegex: [
    '.css$'
  ],
  // ..
}));

// ..
```

Template with some logic

```ejs
<!DOCTYPE html>
<html lang="en" class="noscript incapable">
<head>
  <meta charset="utf-8">
  <title><%= htmlWebpackPlugin.options.title || 'Webpack Test'%></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">

  <!-- CSS LOGIC -->
  <%
  // GET CSS ARRAY IDS THAT SHOULD BE INLINED
  // otherwise we would need to do lookup 2 times

  for (var cssIdx in htmlWebpackPlugin.files.css) {
    var cssIdxToInline = [];
    // Get path of this file
    var fullPublicPath = htmlWebpackPlugin.files.css[cssIdx];
    // For all inlineCSSRegex specified in HtmlWebpackPlugin check for match
    // We allow regex to find in full public path, not just filename, as it may be handy
    for (var rIdx in htmlWebpackPlugin.options.inlineCSSRegex) {
      var regExp = new RegExp(htmlWebpackPlugin.options.inlineCSSRegex[rIdx]);
      if (regExp.test(fullPublicPath)) {
        cssIdxToInline.push(cssIdx);
        break; // break on first, but sometimes maybe scan all?
      }
    }
  }
  %>

  <% for (var cssIdx in htmlWebpackPlugin.files.css) {
    // INLINE CSS
    // If this cssIdx is not in cssIdxToInline, then skip
    if (!cssIdxToInline.includes(cssIdx)) {
      continue;
    }
    // Get path of this file
    var fullPublicPath = htmlWebpackPlugin.files.css[cssIdx];
    // Get filename
    var fileName = /[^/]*$/.exec(fullPublicPath)[0];
    // Get source
    var source = compilation.assets[fileName].source();
    // Echo source in style tags
  %>
    <style>
      <%= source %>
    </style>
  <% } %>

  <% for (var cssIdx in htmlWebpackPlugin.files.css) {
    // LINK CSS
    // If this cssIdx is in cssIdxToInline, then skip
    if (cssIdxToInline.includes(cssIdx)) {
      continue;
    }
  %>
    <link href="<%= htmlWebpackPlugin.files.css[cssIdx] %>" rel="stylesheet" type="text/css">
  <% } %>
  <!-- // CSS LOGIC -->

</head>
<body>
  <div class="app"></div>
  <script>
    window.__TEMPLATE_DATA__ = {};
  </script>

  <% for (var item in htmlWebpackPlugin.options.scripts) { %><%
      if (typeof item === 'string' || item instanceof String) { item = { src: item, type: 'text/javascript' } } %>
    <script<% for (var key in item) { %> <%= key %>="<%= item[key] %>"<% } %>></script>
  <% } %>

  <% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
    <script async src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
  <% } %>

</body>
</html>
```

Thus 

* you can ditch any CSS inline plugins if inlining is needed with custom templates as no currently works with webpack 4 and custom templates due to various reasons
* if fast test inlining with no custom template needed, then  _html-webpack-inline-source-plugin_ works with webpack 4 and _mini-css-extract-plugin_

**Comment by numical** [comment]
Hi all.  Finally, finally, finally, webpack 4.x support in version 4.0.1 of this plugin.
Sorry for the long, long delay.

**Pull request closed without merging**
