### PR TITLE
option style tag custom attrs

### PR DESCRIPTION
**Pull request by zicjin**

### CODE REVIEW

**Comment by numical** [comment]
Hi, is this still something you'd wish to add?  If so, we need to add some tests to this PR.

**Comment by dzotos** [comment]
Hi, any update? It's really useful feature. Trying to find a way to pass AMP custom attributes.

**Comment by numical** [comment]
HI, happy to look at an updated PR (**with tests**).  No time myself I'm afraid.

**Comment by numical** [comment]
Pk - no progress on this - closing for lack of interest.

**Pull request closed without merging**
